phishing_radar:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "md:{{ env_var('MD_CATALOG', 'phishing_radar') }}?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: "{{ env_var('MD_DATABASE', 'main') }}"
      threads: 4
